package com.chanter.common.events;

import java.sql.Timestamp;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import org.springframework.transaction.support.TransactionTemplate;

/** Source-local durable delivery. Claims never hold a transaction over network I/O. */
public final class DurableOutbox {
    public static final String SCHEMA = """
        CREATE TABLE durable_outbox (
            revision BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id UUID NOT NULL UNIQUE, destination VARCHAR(32) NOT NULL,
            kind VARCHAR(40) NOT NULL, aggregate_key VARCHAR(300) NOT NULL,
            payload TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
            available_at TIMESTAMP WITH TIME ZONE NOT NULL, status VARCHAR(16) NOT NULL,
            attempts INT NOT NULL DEFAULT 0, lease_token UUID, lease_until TIMESTAMP WITH TIME ZONE,
            last_error VARCHAR(80), delivered_at TIMESTAMP WITH TIME ZONE,
            replay_count INT NOT NULL DEFAULT 0, replayed_at TIMESTAMP WITH TIME ZONE
        )
        """;
    private final JdbcTemplate jdbc;
    private final TransactionTemplate tx;
    private final String producer;
    private final Clock clock;

    public DurableOutbox(JdbcTemplate jdbc, TransactionTemplate tx, String producer, Clock clock) {
        this.jdbc = jdbc;
        this.tx = tx;
        this.producer = producer;
        this.clock = clock;
    }

    public UUID append(String destination, String kind, String aggregateKey, String payload) {
        if (!TransactionSynchronizationManager.isActualTransactionActive()) {
            throw new IllegalStateException("Outbox event requires the source transaction");
        }
        if (!java.util.Set.of("search", "notification").contains(destination)) {
            throw new IllegalArgumentException("Unknown event destination");
        }
        UUID id = UUID.randomUUID();
        new DurableEvent(id, 1, producer, 1, kind, aggregateKey, payload).validate();
        jdbc.update("""
            INSERT INTO durable_outbox (id, destination, kind, aggregate_key, payload, created_at, available_at, status)
            VALUES (?, ?, ?, ?, ?, ?, ?, 'PENDING')
            """, id, destination, kind, aggregateKey, payload, timestamp(clock.instant()), timestamp(clock.instant()));
        return id;
    }

    public Optional<Delivery> claim() {
        return tx.execute(status -> {
            Instant now = clock.instant();
            // Expired final attempts become visible failures, rather than retrying forever after worker crashes.
            jdbc.update("""
                UPDATE durable_outbox SET status='FAILED', last_error='LEASE_EXPIRED', lease_token=NULL
                WHERE status='SENDING' AND lease_until <= ? AND attempts >= 8
                """, timestamp(now));
            List<Delivery> rows = jdbc.query("""
                SELECT * FROM durable_outbox
                WHERE (status='PENDING' AND available_at <= ?) OR (status='SENDING' AND lease_until <= ? AND attempts < 8)
                ORDER BY revision LIMIT 1 FOR UPDATE
                """, (rs, index) -> new Delivery(new DurableEvent(rs.getObject("id", UUID.class), 1, producer,
                    rs.getLong("revision"), rs.getString("kind"), rs.getString("aggregate_key"), rs.getString("payload")),
                    rs.getString("destination"), UUID.randomUUID(), rs.getInt("attempts") + 1), timestamp(now), timestamp(now));
            if (rows.isEmpty()) return Optional.empty();
            Delivery delivery = rows.getFirst();
            jdbc.update("""
                UPDATE durable_outbox SET status='SENDING', attempts=?, lease_token=?, lease_until=? WHERE id=?
                """, delivery.attempt(), delivery.leaseToken(), timestamp(now.plusSeconds(60)), delivery.event().id());
            return Optional.of(delivery);
        });
    }

    public void delivered(Delivery delivery) {
        jdbc.update("""
            UPDATE durable_outbox SET status='DELIVERED', delivered_at=?, last_error=NULL, lease_token=NULL,
                payload='{}' WHERE id=? AND lease_token=? AND status='SENDING'
            """, timestamp(clock.instant()), delivery.event().id(), delivery.leaseToken());
    }

    public void failed(Delivery delivery, String errorCode) {
        if (errorCode == null || !errorCode.matches("[A-Z0-9_]{1,80}")) errorCode = "DELIVERY_FAILED";
        jdbc.update("""
            UPDATE durable_outbox SET status=?, available_at=?, last_error=?, lease_token=NULL
            WHERE id=? AND lease_token=? AND status='SENDING'
            """, delivery.attempt() >= 8 ? "FAILED" : "PENDING",
            timestamp(clock.instant().plusSeconds(Math.min(300, 1L << delivery.attempt()))),
            errorCode, delivery.event().id(), delivery.leaseToken());
    }

    public boolean replay(UUID id) {
        return jdbc.update("""
            UPDATE durable_outbox SET status='PENDING', attempts=0, available_at=?, last_error=NULL,
                replay_count=replay_count+1, replayed_at=? WHERE id=? AND status='FAILED'
            """, timestamp(clock.instant()), timestamp(clock.instant()), id) == 1;
    }

    public List<Failure> failures() {
        return jdbc.query("""
            SELECT id, kind, destination, attempts, last_error, replay_count FROM durable_outbox
            WHERE status='FAILED' ORDER BY revision LIMIT 100
            """, (rs, index) -> new Failure(rs.getObject("id", UUID.class), rs.getString("kind"),
                rs.getString("destination"), rs.getInt("attempts"), rs.getString("last_error"), rs.getInt("replay_count")));
    }

    public Stats stats() {
        return jdbc.queryForObject("""
            SELECT COUNT(CASE WHEN status='PENDING' THEN 1 END) pending,
                COUNT(CASE WHEN status='SENDING' THEN 1 END) sending,
                COUNT(CASE WHEN status='FAILED' THEN 1 END) failed,
                COUNT(CASE WHEN status='DELIVERED' THEN 1 END) delivered,
                MIN(CASE WHEN status IN ('PENDING','SENDING') THEN created_at END) oldest,
                MAX(delivered_at) last_success FROM durable_outbox
            """, (rs, index) -> new Stats(rs.getLong("pending"), rs.getLong("sending"), rs.getLong("failed"),
                rs.getLong("delivered"), rs.getTimestamp("oldest") == null ? null : rs.getTimestamp("oldest").toInstant(),
                rs.getTimestamp("last_success") == null ? null : rs.getTimestamp("last_success").toInstant()));
    }

    private static Timestamp timestamp(Instant instant) { return Timestamp.from(instant); }
    public record Delivery(DurableEvent event, String destination, UUID leaseToken, int attempt) { }
    public record Failure(UUID id, String kind, String destination, int attempts, String lastError, int replayCount) { }
    public record Stats(long pending, long sending, long failed, long delivered, Instant oldestPending, Instant lastSuccess) { }
}
