import { useMemo, useState, type FormEvent } from 'react'
import { Check, CheckCheck, Mic, MicOff, Paperclip, Phone, Plus, Send, Smile, UserPlus, Video, X } from 'lucide-react'

import { useAuthStore } from '../../../stores/auth-store'
import { useFriendsHub } from '../../friends/hooks/use-friends-hub'
import { formatFriendLabel } from '../../friends/friend-label'
import { V2Avatar } from '../components/V2Avatar'

const demoFriends = [
  ['demo-alex','Alex Chen','blue',true],['demo-priya','Priya Sharma','purple',true],['demo-jordan','Jordan Kim','amber',true],['demo-taylor','Taylor Johnson','green',false],['demo-casey','Casey Nguyen','blue',false],['demo-riley','Riley Patel','purple',false],['demo-morgan','Morgan Lee','amber',false],['demo-jamie','Jamie Park','green',false],['demo-avery','Avery Rodriguez','purple',false],['demo-drew','Drew Smith','blue',false],['demo-quinn','Quinn Davis','amber',false],['demo-cameron','Cameron White','green',false],
] as const
const initialMessages = [
  {id:'d1',body:'Want to study calculus tonight?',own:false,time:'6:32 PM'}, {id:'d2',body:'Yeah integrals are killing me',own:true,time:'6:33 PM'}, {id:'d3',body:'Call at 7?',own:false,time:'6:34 PM'}, {id:'d4',body:'Perfect',own:true,time:'6:34 PM'},
]

export function FriendsPage() {
  const hub=useFriendsHub(); const user=useAuthStore((state)=>state.user); const [tab,setTab]=useState<'friends'|'pending'>('friends'); const [selectedDemo,setSelectedDemo]=useState('demo-alex'); const [draft,setDraft]=useState(''); const [demoMessages,setDemoMessages]=useState(initialMessages); const [showAdd,setShowAdd]=useState(false); const [requestHandled,setRequestHandled]=useState<string[]>([])
  const rows=useMemo(()=>hub.friends.length?hub.friends.map((friend,index)=>({id:friend.friendUserId,name:['Alex Chen','Priya Sharma','Jordan Kim'][index]??formatFriendLabel(friend.friendUserId),tone:(['blue','purple','amber','green'][index%4] as 'blue'|'purple'|'amber'|'green'),online:hub.presenceByFriendId[friend.friendUserId]==='online',real:true})):demoFriends.map(([id,name,tone,online])=>({id,name,tone,online,real:false})),[hub.friends,hub.presenceByFriendId])
  const activeId=hub.selectedFriendId ?? selectedDemo; const active=rows.find((friend)=>friend.id===activeId) ?? rows[0]; const liveMessages=hub.selectedFriendId?hub.messages:[]
  const select=(id:string,real:boolean)=>{if(real)hub.selectFriend(id);else setSelectedDemo(id)}
  const submit=(event:FormEvent)=>{event.preventDefault();const body=draft.trim();if(!body)return;if(hub.selectedFriendId){void hub.sendMessage(body).then((sent)=>sent&&setDraft(''))}else{setDemoMessages((items)=>[...items,{id:`d${items.length+1}`,body,own:true,time:new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}]);setDraft('')}}
  const realMessages=liveMessages.map((message)=>({id:message.id,body:message.body,own:message.senderUserId===user?.id,time:new Date(message.sentAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}))
  return <div className="friends-page"><aside className="friends-list-pane"><header><h1>Friends</h1><button type="button" onClick={()=>setShowAdd(true)}>Add friend <Plus /></button></header><nav><button type="button" className={tab==='friends'?'active':''} onClick={()=>setTab('friends')}>Friends</button><button type="button" className={tab==='pending'?'active':''} onClick={()=>setTab('pending')}>Pending requests <b>2</b></button></nav>{tab==='friends'?<div className="friends-list"><h2>ONLINE <b>{rows.filter((friend)=>friend.online).length}</b></h2>{rows.filter((friend)=>friend.online).map((friend)=><FriendButton key={friend.id} friend={friend} active={active?.id===friend.id} onClick={()=>select(friend.id,friend.real)} />)}<h2>ALL <b>{rows.length}</b></h2>{rows.filter((friend)=>!friend.online).map((friend)=><FriendButton key={friend.id} friend={friend} active={active?.id===friend.id} onClick={()=>select(friend.id,friend.real)} />)}</div>:<div className="pending-friends"><h2>PENDING REQUESTS</h2>{[['req-priya','Morgan Liu'],['req-noah','Noah Williams']].filter(([id])=>!requestHandled.includes(id)).map(([id,name])=><article key={id}><V2Avatar name={name} tone="purple" size="md" /><span><strong>{name}</strong><small>Spring Bootcamp Hub</small></span><button type="button" onClick={()=>setRequestHandled((items)=>[...items,id])}><Check /></button><button type="button" onClick={()=>setRequestHandled((items)=>[...items,id])}><X /></button></article>)}{requestHandled.length===2?<p>No pending requests.</p>:null}</div>}</aside><section className="dm-pane"><header><V2Avatar name={active?.name??'Friend'} tone={active?.tone??'blue'} size="lg" online={active?.online} /><div><h2>{active?.name??'Select a friend'}</h2><p>{active?.online?'Online':'Offline'}</p></div><button type="button" onClick={hub.startCall} disabled={!hub.selectedFriendId||hub.connectionStatus!=='connected'}><Phone /></button><button type="button" title="Video calls are not available yet" disabled><Video /></button></header>{hub.error?<p className="inline-error">{hub.error}</p>:null}<div className="dm-message-list"><span className="today-divider">Today</span>{(realMessages.length?realMessages:demoMessages).map((message)=><article className={message.own?'own':''} key={message.id}>{!message.own?<V2Avatar name={active?.name??'Friend'} tone={active?.tone??'blue'} size="md" />:null}<div><p>{message.body}</p><time>{message.time}{message.own?<CheckCheck />:null}</time></div></article>)}</div><form onSubmit={submit}><button type="button"><Paperclip /></button><input value={draft} onChange={(event)=>setDraft(event.target.value)} placeholder={`Message ${active?.name??'friend'}…`} /><button type="button"><Smile /></button><button type="submit" className="send" disabled={!draft.trim()||hub.isSending}><Send /></button></form></section>{showAdd?<AddFriendModal onClose={()=>setShowAdd(false)} />:null}{hub.callState.phase!=='idle'?<CallModal hub={hub} friendName={active?.name??'Friend'} />:null}</div>
}
type FriendRow={id:string;name:string;tone:'blue'|'purple'|'amber'|'green';online:boolean;real:boolean}
function FriendButton({friend,active,onClick}:{friend:FriendRow;active:boolean;onClick:()=>void}){return <button type="button" className={active?'active':''} onClick={onClick}><V2Avatar name={friend.name} tone={friend.tone} size="md" online={friend.online} /><span>{friend.name}</span></button>}
function AddFriendModal({onClose}:{onClose:()=>void}){const [sent,setSent]=useState(false);return <div className="v2-modal-backdrop"><form className="add-friend-modal" onSubmit={(event)=>{event.preventDefault();setSent(true)}}><button type="button" className="modal-close" onClick={onClose}><X /></button><UserPlus /><h2>{sent?'Request sent':'Add a friend'}</h2><p>{sent?'They will appear here after accepting.':'Connect with someone from a shared Study Server.'}</p>{!sent?<input required placeholder="Email or user ID" />:null}<footer><button type="button" className="v2-outline-button" onClick={onClose}>{sent?'Done':'Cancel'}</button>{!sent?<button type="submit" className="v2-primary-button">Send request</button>:null}</footer></form></div>}
type FriendsHook=ReturnType<typeof useFriendsHub>
function CallModal({hub,friendName}:{hub:FriendsHook;friendName:string}){const incoming=hub.callState.phase==='incoming_ringing';const inCall=hub.callState.phase==='in_call';return <div className="v2-modal-backdrop"><section className="dm-call-modal"><V2Avatar name={friendName} tone="blue" size="lg" online /><h2>{friendName}</h2><p>{incoming?'Incoming call…':inCall?'Connected':hub.callState.phase==='connecting'?'Connecting audio…':'Ringing…'}</p>{hub.callError?<p className="modal-error">{hub.callError}</p>:null}<div>{incoming?<button type="button" className="accept" onClick={hub.acceptCall}><Phone /></button>:null}{inCall?<button type="button" onClick={()=>void hub.toggleCallMute()}>{hub.isMuted?<MicOff />:<Mic />}</button>:null}<button type="button" className="hangup" onClick={inCall?hub.hangUpCall:hub.declineCall}><Phone /></button></div></section></div>}
