User clamav
Foreground yes
DatabaseDirectory /var/lib/clamav
TemporaryDirectory /tmp
PidFile /tmp/clamd.pid
LocalSocket /run/clamav/clamd.sock
LocalSocketGroup chanter-media
LocalSocketMode 660
FixStaleSocket yes
LogTime yes
SelfCheck 60
ConcurrentDatabaseReload no
MaxThreads 2
MaxQueue 8
StreamMaxLength 10M
MaxScanSize 40M
MaxFileSize 10M
MaxRecursion 16
MaxFiles 1024
MaxScanTime 20000
ReadTimeout 20
CommandReadTimeout 5
SendBufTimeout 500
AlertExceedsMax yes
AlertEncryptedArchive yes
AlertEncryptedDoc yes
