CREATE TABLE durable_outbox (
            revision BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id UUID NOT NULL UNIQUE, destination VARCHAR(32) NOT NULL,
            kind VARCHAR(40) NOT NULL, aggregate_key VARCHAR(300) NOT NULL,
            payload TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
            available_at TIMESTAMP WITH TIME ZONE NOT NULL, status VARCHAR(16) NOT NULL,
            attempts INT NOT NULL DEFAULT 0, lease_token UUID, lease_until TIMESTAMP WITH TIME ZONE,
            last_error VARCHAR(80), delivered_at TIMESTAMP WITH TIME ZONE,
            replay_count INT NOT NULL DEFAULT 0, replayed_at TIMESTAMP WITH TIME ZONE
        );
CREATE INDEX idx_outbox_delivery ON durable_outbox (status, available_at, revision);

CREATE INDEX idx_outbox_expired_lease ON durable_outbox(status, lease_until, revision);
