import { useState, type FormEvent } from 'react'
import { CalendarDays, ChevronRight, Ellipsis, Hash, Heart, MessageCircle, Plus, Search, Send, Smile, Sprout, UsersRound, Volume2 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

import { useChannelConversation } from '../../../shell/hooks/use-channel-conversation'
import { V2Avatar } from '../../components/V2Avatar'
import { useV2Community } from '../../layouts/v2-community-context'

export { CommunityEventsPage } from './CommunityEventsPage'

const announcements = [
  { author:'Dr. Alex Johnson', role:'OWNER', age:'2h ago', title:'Hackathon signups are open!', body:'Team up across CS 101 and MATH 201 — details inside.', likes:24, comments:8, tone:'amber' as const },
  { author:'Priya Patel', role:'ADMIN', age:'1d ago', title:'Study rooms now available', body:'Book a room in the Hub for group study or office hours.', likes:18, comments:6, tone:'purple' as const },
  { author:'Marcus Webb', role:'ADMIN', age:'2d ago', title:'Midterm review sessions this week', body:'See the schedule and drop-in times for CS 101 and MATH 201.', likes:32, comments:12, tone:'green' as const },
]
const members = [
  ['Dr. Alex Johnson','OWNER','amber'],['Priya Patel','ADMIN','purple'],['Marcus Webb','ADMIN','green'],['Maria Gonzalez','TA','purple'],['Sam You','','blue'],['Daniel Anderson','','green'],['Maya Gonzalez','','purple'],['Jordan Kim','','blue'],['Noah Smith','','amber'],
] as const
export function CommunityAnnouncementsPage() { return <div className="announcements-layout"><main>{announcements.map((item) => <article className="announcement-card" key={item.title}><V2Avatar name={item.author} tone={item.tone} size="lg" /><div><p><strong>{item.author}</strong><b>{item.role}</b><time>{item.age}</time><button type="button"><Ellipsis /></button></p><h2>{item.title}</h2><span>{item.body}</span>{item.title.startsWith('Hackathon') ? <button type="button" className="v2-primary-button">Sign up</button> : null}</div><footer><span><Heart />{item.likes}</span><span><MessageCircle />{item.comments} comments</span></footer></article>)}</main><aside><section><h2><Sprout />About</h2><p>Bootcamp community for spring courses.</p><p><CalendarDays />Created Jan 2026</p><p><UsersRound />3 courses</p><p><UsersRound />214 members</p></section><section><h2><CalendarDays />Upcoming events</h2><p className="upcoming-community-event"><CalendarDays /><span><strong>Open Events</strong><small>See the Events tab for durable RSVPs</small></span></p><button type="button">View all events <ChevronRight /></button></section></aside></div> }

export function CommunityLoungePage() {
  const { navigation } = useV2Community(); const textChannels = navigation?.studyServerChannels.filter((channel) => channel.kind === 'TEXT') ?? []; const voiceChannels = navigation?.studyServerChannels.filter((channel) => channel.kind === 'VOICE') ?? []; const [selectedId,setSelectedId]=useState(textChannels[0]?.id ?? 'lounge-demo'); const selected=textChannels.find((channel)=>channel.id===selectedId) ?? textChannels[0]; const conversation=useChannelConversation('study',selected?.id); const [draft,setDraft]=useState(''); const submit=(event:FormEvent)=>{event.preventDefault();void conversation.sendMessage(draft).then((sent)=>sent&&setDraft(''))}; const demo=[['Priya Patel','Anyone else stuck on problem set 2?','ADMIN','purple'],['Marcus Webb','Welcome to the hub — say hi in #introductions','ADMIN','green'],['Maria Gonzalez','Study room has 3 people if you want to pair','TA','amber']] as const;
  return <div className="community-lounge-layout"><aside><h2>CHANNELS</h2>{(textChannels.length?textChannels:[{id:'lounge-demo',name:'lounge',kind:'TEXT' as const},{id:'general-demo',name:'general',kind:'TEXT' as const},{id:'intro-demo',name:'introductions',kind:'TEXT' as const},{id:'off-demo',name:'off-topic',kind:'TEXT' as const}]).map((channel,index)=><button type="button" key={channel.id} className={(selected?.id??'lounge-demo')===channel.id?'active':undefined} onClick={()=>setSelectedId(channel.id)}><Hash />{channel.name}{index===1?<b>2</b>:null}</button>)}<hr /><h2>VOICE</h2>{(voiceChannels.length?voiceChannels:[{id:'voice-demo',name:'Community Lounge',kind:'VOICE' as const}]).map((channel)=><button type="button" className="community-voice" key={channel.id}><Volume2 />{channel.name}</button>)}</aside><section><div className="community-message-list">{conversation.messages.length?conversation.messages.map((message,index)=><CommunityMessage key={message.id} name={`Member ${index+1}`} body={message.body} role="" tone="blue" />):demo.map(([name,body,role,tone])=><CommunityMessage key={name} name={name} body={body} role={role} tone={tone} />)}</div><form onSubmit={submit}><button type="button"><Plus /></button><input value={draft} onChange={(event)=>setDraft(event.target.value)} placeholder={`Message #${selected?.name??'lounge'}`} /><button type="button"><Smile /></button><button type="submit" className="send"><Send /></button></form></section></div>
}
function CommunityMessage({name,body,role,tone}:{name:string;body:string;role:string;tone:'blue'|'green'|'amber'|'purple'}) { return <article className="community-message"><V2Avatar name={name} tone={tone} size="lg" /><div><p><strong>{name}</strong>{role?<b>{role}</b>:null}<time>2:14 PM</time></p><span>{body}</span></div></article> }

export function CommunityMembersPage() { const navigate=useNavigate(); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const visible=members.filter(([name,role])=>name.toLowerCase().includes(query.toLowerCase())&&(filter==='All'||filter==='Staff'?filter==='All'||Boolean(role):true)); return <div className="community-members-page"><label><Search /><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search members…" /></label><div className="member-filters">{['All','Active','Online','Staff','Learners'].map((value)=><button type="button" className={filter===value?'active':undefined} onClick={()=>setFilter(value)} key={value}>{value}</button>)}</div><h2>STAFF</h2>{visible.filter(([,role])=>role).map(([name,role,tone])=><MemberRow key={name} name={name} role={role} tone={tone} />)}<h2>LEARNERS</h2>{visible.filter(([,role])=>!role).map(([name,role,tone],index)=><MemberRow key={name} name={name} role={role} tone={tone} current={index===0} onMessage={()=>navigate('/app/friends')} />)}<p className="member-more"><UsersRound />+208 more</p></div> }
function MemberRow({name,role,tone,current,onMessage}:{name:string;role:string;tone:'blue'|'green'|'amber'|'purple';current?:boolean;onMessage?:()=>void}) { return <article className={current?'current':''}><V2Avatar name={name} tone={tone} size="md" online /><strong>{name}</strong>{role?<b>{role}</b>:null}{onMessage&&!current?<button type="button" onClick={onMessage}><MessageCircle />Message</button>:null}</article> }

export { CommunityDiscoverPage } from './CommunityDiscoverPage'
