import { useState, type FormEvent } from 'react'
import { CalendarDays, Check, ChevronRight, Ellipsis, Hash, Heart, MapPin, MessageCircle, Plus, Search, Send, Share2, Smile, Sprout, UsersRound, Volume2, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'

import { useChannelConversation } from '../../../shell/hooks/use-channel-conversation'
import { V2Avatar } from '../../components/V2Avatar'
import { useV2Community } from '../../layouts/v2-community-context'

const announcements = [
  { author:'Dr. Alex Johnson', role:'OWNER', age:'2h ago', title:'Hackathon signups are open!', body:'Team up across CS 101 and MATH 201 — details inside.', likes:24, comments:8, tone:'amber' as const },
  { author:'Priya Patel', role:'ADMIN', age:'1d ago', title:'Study rooms now available', body:'Book a room in the Hub for group study or office hours.', likes:18, comments:6, tone:'purple' as const },
  { author:'Marcus Webb', role:'ADMIN', age:'2d ago', title:'Midterm review sessions this week', body:'See the schedule and drop-in times for CS 101 and MATH 201.', likes:32, comments:12, tone:'green' as const },
]
const events = [
  { id:'hackathon', date:'Fri, Jul 18', time:'2:00 PM – 6:00 PM', title:'Hackathon kickoff', place:'Office hours — CS 101', going:24 },
  { id:'guest-talk', date:'Tue, Jul 22', time:'6:00 PM – 7:30 PM', title:'Guest talk: AI in industry', place:'CS 101', going:42 },
  { id:'midterm', date:'Thu, Jul 24', time:'2:00 PM – 3:30 PM', title:'Midterm review: CS 101', place:'Office hours — CS 101', going:18 },
  { id:'study-group', date:'Mon, Jul 28', time:'10:00 AM – 12:00 PM', title:'Study group: Linear Algebra', place:'Library Room 204', going:12 },
]
const members = [
  ['Dr. Alex Johnson','OWNER','amber'],['Priya Patel','ADMIN','purple'],['Marcus Webb','ADMIN','green'],['Maria Gonzalez','TA','purple'],['Sam You','','blue'],['Daniel Anderson','','green'],['Maya Gonzalez','','purple'],['Jordan Kim','','blue'],['Noah Smith','','amber'],
] as const
export function CommunityAnnouncementsPage() { return <div className="announcements-layout"><main>{announcements.map((item) => <article className="announcement-card" key={item.title}><V2Avatar name={item.author} tone={item.tone} size="lg" /><div><p><strong>{item.author}</strong><b>{item.role}</b><time>{item.age}</time><button type="button"><Ellipsis /></button></p><h2>{item.title}</h2><span>{item.body}</span>{item.title.startsWith('Hackathon') ? <button type="button" className="v2-primary-button">Sign up</button> : null}</div><footer><span><Heart />{item.likes}</span><span><MessageCircle />{item.comments} comments</span></footer></article>)}</main><aside><section><h2><Sprout />About</h2><p>Bootcamp community for spring courses.</p><p><CalendarDays />Created Jan 2026</p><p><UsersRound />3 courses</p><p><UsersRound />214 members</p></section><section><h2><CalendarDays />Upcoming events</h2>{events.slice(0,3).map((event) => <p className="upcoming-community-event" key={event.id}><CalendarDays /><span><strong>{event.title}</strong><small>{event.date} · {event.time.split(' – ')[0]}</small></span></p>)}<button type="button">View all events <ChevronRight /></button></section></aside></div> }

export function CommunityLoungePage() {
  const { navigation } = useV2Community(); const textChannels = navigation?.studyServerChannels.filter((channel) => channel.kind === 'TEXT') ?? []; const voiceChannels = navigation?.studyServerChannels.filter((channel) => channel.kind === 'VOICE') ?? []; const [selectedId,setSelectedId]=useState(textChannels[0]?.id ?? 'lounge-demo'); const selected=textChannels.find((channel)=>channel.id===selectedId) ?? textChannels[0]; const conversation=useChannelConversation('study',selected?.id); const [draft,setDraft]=useState(''); const submit=(event:FormEvent)=>{event.preventDefault();void conversation.sendMessage(draft).then((sent)=>sent&&setDraft(''))}; const demo=[['Priya Patel','Anyone else stuck on problem set 2?','ADMIN','purple'],['Marcus Webb','Welcome to the hub — say hi in #introductions','ADMIN','green'],['Maria Gonzalez','Study room has 3 people if you want to pair','TA','amber']] as const;
  return <div className="community-lounge-layout"><aside><h2>CHANNELS</h2>{(textChannels.length?textChannels:[{id:'lounge-demo',name:'lounge',kind:'TEXT' as const},{id:'general-demo',name:'general',kind:'TEXT' as const},{id:'intro-demo',name:'introductions',kind:'TEXT' as const},{id:'off-demo',name:'off-topic',kind:'TEXT' as const}]).map((channel,index)=><button type="button" key={channel.id} className={(selected?.id??'lounge-demo')===channel.id?'active':undefined} onClick={()=>setSelectedId(channel.id)}><Hash />{channel.name}{index===1?<b>2</b>:null}</button>)}<hr /><h2>VOICE</h2>{(voiceChannels.length?voiceChannels:[{id:'voice-demo',name:'Community Lounge',kind:'VOICE' as const}]).map((channel)=><button type="button" className="community-voice" key={channel.id}><Volume2 />{channel.name}</button>)}</aside><section><div className="community-message-list">{conversation.messages.length?conversation.messages.map((message,index)=><CommunityMessage key={message.id} name={`Member ${index+1}`} body={message.body} role="" tone="blue" />):demo.map(([name,body,role,tone])=><CommunityMessage key={name} name={name} body={body} role={role} tone={tone} />)}</div><form onSubmit={submit}><button type="button"><Plus /></button><input value={draft} onChange={(event)=>setDraft(event.target.value)} placeholder={`Message #${selected?.name??'lounge'}`} /><button type="button"><Smile /></button><button type="submit" className="send"><Send /></button></form></section></div>
}
function CommunityMessage({name,body,role,tone}:{name:string;body:string;role:string;tone:'blue'|'green'|'amber'|'purple'}) { return <article className="community-message"><V2Avatar name={name} tone={tone} size="lg" /><div><p><strong>{name}</strong>{role?<b>{role}</b>:null}<time>2:14 PM</time></p><span>{body}</span></div></article> }

export function CommunityEventsPage() { const {studyServerCapabilities}=useV2Community(); const canManageEvents=studyServerCapabilities?.canManageEvents??false; const [filter,setFilter]=useState('Upcoming'); const [eventItems,setEventItems]=useState(events); const [selected,setSelected]=useState<typeof events[number]|null>(null); const [editing,setEditing]=useState<typeof events[number]|null|undefined>(undefined); const [going,setGoing]=useState<string[]>(events.map((event)=>event.id)); const saveEvent=(event:typeof events[number])=>{setEventItems((items)=>items.some((item)=>item.id===event.id)?items.map((item)=>item.id===event.id?event:item):[event,...items]);setEditing(undefined)}; return <div className="community-events-page"><div className="community-event-toolbar"><div className="event-filters">{['Upcoming','Past','Going'].map((value)=><button type="button" key={value} className={filter===value?'active':undefined} onClick={()=>setFilter(value)}>{value}</button>)}</div>{canManageEvents?<button type="button" className="v2-primary-button" onClick={()=>setEditing(null)}><Plus />Create event</button>:null}</div><div className="event-list">{eventItems.map((event)=><article key={event.id} onClick={()=>setSelected(event)}><span><CalendarDays /></span><div><small>{event.date} · {event.time}</small><h2>{event.title}</h2><p><MapPin />{event.place}<b><UsersRound />Open to all</b></p></div>{canManageEvents?<button type="button" className="event-edit-link" onClick={(click)=>{click.stopPropagation();setEditing(event)}}>Edit</button>:null}<div><button type="button" className={going.includes(event.id)?'active':''} onClick={(click)=>{click.stopPropagation();setGoing((items)=>items.includes(event.id)?items.filter((id)=>id!==event.id):[...items,event.id])}}>{going.includes(event.id)?'Going':'Interested'}</button><small>{event.going} going</small></div></article>)}</div>{selected?<EventDetailModal event={selected} onClose={()=>setSelected(null)} />:null}{editing!==undefined?<CreateEventModal event={editing} onSave={saveEvent} onClose={()=>setEditing(undefined)} />:null}</div> }
function EventDetailModal({event,onClose}:{event:typeof events[number];onClose:()=>void}) { return <div className="v2-modal-backdrop"><section className="event-detail-modal"><button type="button" className="modal-close" onClick={onClose}><X /></button><header><span><CalendarDays /></span><div><h2>{event.title}</h2><p><CalendarDays />Friday, July 18, 2026</p><p><CalendarDays />{event.time}</p><p><MapPin />{event.place}</p></div></header><div className="event-host"><V2Avatar name="Priya Patel" tone="purple" size="md" /><p>Hosted by <strong>Priya Patel</strong><b>ADMIN</b><small>Spring Bootcamp Hub</small></p></div><hr /><h3>About this event</h3><p>Kick off the weekend hackathon! We’ll go over the challenge, form teams, and share tips to get started. Open to all CS 101 and MATH 201 students.</p><div className="event-tags"><b>CS 101</b><b>MATH 201</b></div><div className="event-going"><UsersRound />{event.going} going <b><Check />Going</b></div><footer><button type="button"><CalendarDays />Add to calendar</button><button type="button"><Share2 />Share</button><button type="button" className="v2-primary-button" onClick={onClose}>Close</button></footer></section></div> }

export function CommunityMembersPage() { const navigate=useNavigate(); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All'); const visible=members.filter(([name,role])=>name.toLowerCase().includes(query.toLowerCase())&&(filter==='All'||filter==='Staff'?filter==='All'||Boolean(role):true)); return <div className="community-members-page"><label><Search /><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search members…" /></label><div className="member-filters">{['All','Active','Online','Staff','Learners'].map((value)=><button type="button" className={filter===value?'active':undefined} onClick={()=>setFilter(value)} key={value}>{value}</button>)}</div><h2>STAFF</h2>{visible.filter(([,role])=>role).map(([name,role,tone])=><MemberRow key={name} name={name} role={role} tone={tone} />)}<h2>LEARNERS</h2>{visible.filter(([,role])=>!role).map(([name,role,tone],index)=><MemberRow key={name} name={name} role={role} tone={tone} current={index===0} onMessage={()=>navigate('/app/friends')} />)}<p className="member-more"><UsersRound />+208 more</p></div> }
function MemberRow({name,role,tone,current,onMessage}:{name:string;role:string;tone:'blue'|'green'|'amber'|'purple';current?:boolean;onMessage?:()=>void}) { return <article className={current?'current':''}><V2Avatar name={name} tone={tone} size="md" online /><strong>{name}</strong>{role?<b>{role}</b>:null}{onMessage&&!current?<button type="button" onClick={onMessage}><MessageCircle />Message</button>:null}</article> }

export { CommunityDiscoverPage } from './CommunityDiscoverPage'

function CreateEventModal({event,onSave,onClose}:{event:typeof events[number]|null;onSave:(event:typeof events[number])=>void;onClose:()=>void}) { const [title,setTitle]=useState(event?.title??'Hackathon kickoff'); const [date,setDate]=useState(event?.date??'Fri, Jul 18'); const [time,setTime]=useState(event?.time??'2:00 PM – 6:00 PM'); const [place,setPlace]=useState(event?.place??'Office hours — CS 101'); const [description,setDescription]=useState('Join us for the start of our weekend hackathon! Teams will form, ideas will spark, and we’ll build something awesome together.'); const [hubWide,setHubWide]=useState(true); return <div className="v2-modal-backdrop"><form className="create-event-modal" onSubmit={(submit)=>{submit.preventDefault();onSave({id:event?.id??`event-${Date.now()}`,date,time,title,place,going:event?.going??0})}}><button type="button" className="modal-close" onClick={onClose}><X /></button><h2>{event?'Edit event':'Create event'}</h2><label><span><CalendarDays /></span><div>Event title<input value={title} onChange={(change)=>setTitle(change.target.value)} required /></div></label><div className="create-event-row"><label><span><CalendarDays /></span><div>Date<input value={date} onChange={(change)=>setDate(change.target.value)} /></div></label><label><span><CalendarDays /></span><div>Time<input value={time} onChange={(change)=>setTime(change.target.value)} /></div></label></div><div className="create-event-row"><label><span><MapPin /></span><div>Location<input value={place} onChange={(change)=>setPlace(change.target.value)} /></div></label><label><span><UsersRound /></span><div>Audience<select><option>Open to all</option><option>CS 101 only</option></select></div></label></div><label><span><MessageCircle /></span><div>Description<textarea value={description} onChange={(change)=>setDescription(change.target.value)} /></div></label><label className="hub-wide-event"><span><Sprout /></span><div><strong>Hub-wide event</strong><small>Make this event visible to everyone in the hub.</small></div><button type="button" className={hubWide?'active':''} onClick={()=>setHubWide(!hubWide)}><i /></button></label><footer><button type="button" className="v2-outline-button" onClick={onClose}>Cancel</button><button type="submit" className="v2-primary-button">{event?'Save changes':'Create event'}</button></footer></form></div> }
