CREATE TABLE platform_operator_lock (id INT PRIMARY KEY);
INSERT INTO platform_operator_lock VALUES (1);

CREATE TABLE platform_operators (
    user_id UUID PRIMARY KEY REFERENCES auth_users(id),
    role VARCHAR(16) NOT NULL CHECK (role IN ('REVIEWER', 'ADMIN')),
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    factor_ciphertext VARCHAR(512),
    factor_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    last_factor_counter BIGINT NOT NULL DEFAULT -1,
    factor_attempts INT NOT NULL DEFAULT 0,
    factor_window_started TIMESTAMP WITH TIME ZONE
);

CREATE TABLE platform_step_up (
    token_hash VARCHAR(64) PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES platform_operators(user_id),
    access_token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX platform_step_up_expiry_idx ON platform_step_up(expires_at);

CREATE TABLE moderation_audit (
    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id UUID,
    action VARCHAR(80) NOT NULL,
    target VARCHAR(200) NOT NULL,
    reason VARCHAR(2000) NOT NULL,
    correlation_id UUID NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    before_state VARCHAR(8000) NOT NULL,
    after_state VARCHAR(8000) NOT NULL
);
CREATE INDEX moderation_audit_target_idx ON moderation_audit(target, sequence);

CREATE TABLE moderation_reports (
    id UUID PRIMARY KEY,
    reporter_id UUID NOT NULL,
    target_type VARCHAR(24) NOT NULL CHECK (target_type IN ('USER','DM','MESSAGE','RESOURCE','STUDY_SERVER')),
    target_id UUID NOT NULL,
    reason VARCHAR(2000) NOT NULL,
    evidence VARCHAR(24000) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('NEW','ASSIGNED','RESOLVED','ESCALATED')),
    assigned_to UUID REFERENCES platform_operators(user_id),
    resolution VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX moderation_reports_queue_idx ON moderation_reports(status,created_at,id);
CREATE INDEX moderation_reports_reporter_idx ON moderation_reports(reporter_id,created_at,id);
CREATE INDEX moderation_reports_assignee_idx ON moderation_reports(assigned_to,created_at,id);

CREATE TABLE moderation_notes (
    id UUID PRIMARY KEY,
    report_id UUID NOT NULL REFERENCES moderation_reports(id),
    actor_id UUID NOT NULL,
    body VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX moderation_notes_report_idx ON moderation_notes(report_id,created_at,id);

CREATE TABLE moderation_restrictions (
    id UUID PRIMARY KEY,
    report_id UUID NOT NULL REFERENCES moderation_reports(id),
    target_type VARCHAR(24) NOT NULL CHECK (target_type IN ('USER','DM','MESSAGE','RESOURCE','STUDY_SERVER')),
    target_id UUID NOT NULL,
    actor_id UUID NOT NULL,
    reason VARCHAR(2000) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CHECK(expires_at > starts_at)
);
CREATE INDEX moderation_restrictions_target_idx ON moderation_restrictions(target_type,target_id,expires_at);
