CREATE TABLE data_export_lock (id INT PRIMARY KEY);
INSERT INTO data_export_lock VALUES (1);
CREATE TABLE data_export_account_tombstones (account_id UUID PRIMARY KEY, deleted_at TIMESTAMP WITH TIME ZONE NOT NULL);
CREATE TABLE data_export_snapshots (
    id UUID PRIMARY KEY, account_id UUID NOT NULL, requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(16) NOT NULL, byte_size BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX data_export_expiry ON data_export_snapshots(expires_at);
CREATE TABLE data_export_entries (
    snapshot_id UUID NOT NULL REFERENCES data_export_snapshots(id) ON DELETE CASCADE,
    ordinal INT NOT NULL, entry_path VARCHAR(120) NOT NULL, media_type VARCHAR(100) NOT NULL,
    byte_size BIGINT NOT NULL DEFAULT 0, page_count INT NOT NULL DEFAULT 0, sha256 VARCHAR(64),
    PRIMARY KEY(snapshot_id, ordinal), UNIQUE(snapshot_id, entry_path)
);
CREATE TABLE data_export_entry_scopes (
    snapshot_id UUID NOT NULL, entry_ordinal INT NOT NULL, access_kind VARCHAR(24) NOT NULL, access_id UUID NOT NULL,
    expected_digest VARCHAR(64),
    PRIMARY KEY(snapshot_id,entry_ordinal,access_kind,access_id),
    FOREIGN KEY(snapshot_id,entry_ordinal) REFERENCES data_export_entries(snapshot_id,ordinal) ON DELETE CASCADE
);
CREATE TABLE data_export_pages (
    snapshot_id UUID NOT NULL, entry_ordinal INT NOT NULL, ordinal INT NOT NULL, payload BYTEA NOT NULL,
    PRIMARY KEY(snapshot_id, entry_ordinal, ordinal),
    FOREIGN KEY(snapshot_id, entry_ordinal) REFERENCES data_export_entries(snapshot_id, ordinal) ON DELETE CASCADE
);

CREATE TABLE lifecycle_terminal_journal (
    revision BIGINT PRIMARY KEY, event_id UUID NOT NULL UNIQUE,
    target_kind VARCHAR(16) NOT NULL, target_id UUID NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    retention_policy VARCHAR(40) NOT NULL CHECK(retention_policy='PRESERVE_MODERATION_RECORDS_V1'),
    previous_digest VARCHAR(64) NOT NULL, digest VARCHAR(64) NOT NULL,
    UNIQUE(target_kind,target_id)
);
CREATE TABLE lifecycle_journal_head (
    id INT PRIMARY KEY, revision BIGINT NOT NULL, digest VARCHAR(64) NOT NULL,
    checkpoint_revision BIGINT NOT NULL DEFAULT 0, checkpoint_digest VARCHAR(64) NOT NULL,
    checkpoint_id UUID, checkpoint_at TIMESTAMP WITH TIME ZONE
);
INSERT INTO lifecycle_journal_head(id,revision,digest,checkpoint_digest)
VALUES (1,0,'0000000000000000000000000000000000000000000000000000000000000000',
'0000000000000000000000000000000000000000000000000000000000000000');

CREATE TABLE durable_outbox (
    revision BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id UUID NOT NULL UNIQUE, destination VARCHAR(32) NOT NULL,
    kind VARCHAR(40) NOT NULL, aggregate_key VARCHAR(300) NOT NULL,
    payload TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL, status VARCHAR(16) NOT NULL,
    attempts INT NOT NULL DEFAULT 0, lease_token UUID, lease_until TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(80), delivered_at TIMESTAMP WITH TIME ZONE,
    replay_count INT NOT NULL DEFAULT 0, replayed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE durable_consumer_lock (id INT PRIMARY KEY);
INSERT INTO durable_consumer_lock VALUES (1);
CREATE TABLE durable_event_cursor (
    producer VARCHAR(32) NOT NULL, aggregate_key VARCHAR(300) NOT NULL,
    revision BIGINT NOT NULL, event_id UUID NOT NULL, deleted BOOLEAN NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (producer, aggregate_key)
);

CREATE TABLE lifecycle_export_job_lock (id INT PRIMARY KEY);
INSERT INTO lifecycle_export_job_lock VALUES (1);
CREATE TABLE lifecycle_export_jobs (
    id UUID PRIMARY KEY, account_id UUID NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    state VARCHAR(16) NOT NULL, cancelled_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX lifecycle_export_jobs_owner ON lifecycle_export_jobs(account_id,requested_at);
CREATE TABLE lifecycle_export_parts (
    job_id UUID NOT NULL REFERENCES lifecycle_export_jobs(id) ON DELETE CASCADE,
    source VARCHAR(16) NOT NULL, state VARCHAR(16) NOT NULL, fingerprint VARCHAR(64),
    request_event_id UUID, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY(job_id,source)
);
CREATE TABLE lifecycle_export_downloads (
    job_id UUID PRIMARY KEY REFERENCES lifecycle_export_jobs(id) ON DELETE CASCADE,
    account_id UUID NOT NULL, session_id UUID NOT NULL,
    handle_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    access_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE lifecycle_reapply_head (id INT PRIMARY KEY, revision BIGINT NOT NULL, digest VARCHAR(64) NOT NULL);
INSERT INTO lifecycle_reapply_head VALUES (1,0,'0000000000000000000000000000000000000000000000000000000000000000');
CREATE TABLE lifecycle_reapply_entries (revision BIGINT PRIMARY KEY, digest VARCHAR(64) NOT NULL);
CREATE TABLE lifecycle_terminal_targets (
    target_kind VARCHAR(16) NOT NULL CHECK(target_kind IN ('ACCOUNT','STUDY_SERVER','RESOURCE')), target_id UUID NOT NULL,
    revision BIGINT NOT NULL UNIQUE CHECK(revision>0), event_id UUID NOT NULL UNIQUE, digest VARCHAR(64) NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NOT NULL, cleanup_state VARCHAR(16) NOT NULL CHECK(cleanup_state IN ('PENDING','PRESERVED','COMPLETE')),
    PRIMARY KEY(target_kind,target_id)
);
CREATE TABLE lifecycle_recovery_invalidations (
    recovery_id UUID PRIMARY KEY, revision BIGINT NOT NULL, digest VARCHAR(64) NOT NULL,
    invalidated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE lifecycle_deletion_lock (id INT PRIMARY KEY);
INSERT INTO lifecycle_deletion_lock VALUES (1);
CREATE TABLE lifecycle_deletion_jobs (
    id UUID PRIMARY KEY,account_id UUID NOT NULL,state VARCHAR(24) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    prepare_event_id UUID NOT NULL,terminal_revision BIGINT,terminal_digest VARCHAR(64),
    receipt_hash VARCHAR(64),receipt_expires_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX lifecycle_deletion_jobs_owner ON lifecycle_deletion_jobs(account_id,created_at);
CREATE INDEX lifecycle_deletion_jobs_expiry ON lifecycle_deletion_jobs(state,expires_at);
CREATE TABLE lifecycle_deletion_parts (
    job_id UUID NOT NULL REFERENCES lifecycle_deletion_jobs(id) ON DELETE CASCADE,
    source VARCHAR(16) NOT NULL,state VARCHAR(16) NOT NULL,event_id UUID,
    PRIMARY KEY(job_id,source)
);

CREATE TABLE lifecycle_source_deletions (
    id UUID PRIMARY KEY,
    target_kind VARCHAR(16) NOT NULL CHECK(target_kind IN ('STUDY_SERVER','RESOURCE')),
    target_id UUID NOT NULL,
    terminal_revision BIGINT NOT NULL,
    terminal_digest VARCHAR(64) NOT NULL,
    UNIQUE(target_kind,target_id)
);
CREATE TABLE lifecycle_source_deletion_parts (
    job_id UUID NOT NULL REFERENCES lifecycle_source_deletions(id),
    source VARCHAR(32) NOT NULL,
    state VARCHAR(16) NOT NULL CHECK(state IN ('PENDING','PRESERVED','COMPLETE')),
    event_id UUID,
    PRIMARY KEY(job_id,source)
);
